первый вариант
dl-academy-edu/vt-idiyatov-alexander pull request #2
Opened 2020-01-28 14:24 UTC by IdiyatovAlexandr

жду комментариев, готовлюсь к исправлениям)

2020-01-29 06:44 UTC, tahavn requested changes
Правки ДЗ-2

2020-01-29 06:44 UTC, tahavn commented on Index.html
> +        </h1>
1.Учитывая, что это слайдер, то тег h1 не подходит, т.к. такие заголовки будут на каждом слайде, а h1 должен быть один на странице.
2. тег br использовал верно, но старайся реже его использовать, в данном случае лучше обойтись без него, а текст можно будет перенести если ограничить ширину блока в стилях

2020-01-29 06:44 UTC, tahavn commented on Index.html
> +        <p class="poster-text">Free (continental) USA shipping on all orders of $100 USD or more!</p>
у тегов p одинаковый класс. хотя по дизайну они оформлены по разному, при одинаковых именах классов у тебя не получится их стилизовать по разному.

2020-01-29 06:44 UTC, tahavn commented on Index.html
> +           place for me and i have you and all of the beautiful designers that we work with to thank!</p>
по дизайну там два параграфа

2020-01-29 06:44 UTC, tahavn commented on Index.html
> +        <h3 class="about us-title">about us</h3>
заголовки имеют разный вид, но имеют одинаковый класс, так не получится их стилизовать по разному. можно обратиться по тегу с классом, но так тоже лучше не делать. на случай если СЕО специалист заменит тег заголовка на другой, то стили уже не сработают.

2020-01-29 06:44 UTC, tahavn commented on Index.html
> +        <a class="delivery" href="#">Credit</a>
для удобства стилизации ссылкам лучше дать другой класс, не такой как у основной секции к примеру delivery-link

2020-01-29 06:44 UTC, tahavn commented on Index.html
> +          <a class="products" href="#">ACCESSORIES</a>
для удобства стилизации ссылкам лучше дать другой класс, не такой как у основной секции к примеру products-link

2020-01-29 06:44 UTC, tahavn commented on Index.html
> +          <p class="">Modern finds for the modern home. Curated goods by unique designers <br>
зачем здесь пустой атрибут class?

2020-01-29 06:44 UTC, tahavn commented on Index.html
> +          <p class="">Modern finds for the modern home. Curated goods by unique designers <br>
в теге p вообще крайне не желательно использовать br, также можно ограничить ширину блока с текстом через стили. Сложность с br в том, что они жестко фиксируют перенос строки и при адаптации сайта это может привести к странному виду текста.

2020-01-29 06:44 UTC, tahavn commented on Index.html
> +        <img src="map." alt="map">
расширение картинки не дописал

2020-01-29 06:44 UTC, tahavn commented on Index.html
> +        </ul>
предполагается, что это пункты меню, поэтому должны быть ссылки еще

2020-01-29 06:44 UTC, tahavn commented on Index.html
> +        </p>
1.не верная структура, если предполагается, что-то отправлять то надо использовать from
2. класс connect не очень подходит т.к. такой класс у родительской секции, возникнут сложности при стилизации.
3. для отправки form вместо a потребуется button, только обрати внимание что у button есть type  и для отправки потребуется button  с определенным типом.

2020-01-29 06:44 UTC, tahavn commented on Index.html
> +      <p class="web design">Web Design — Direct Line Development</p>
лучше название студии поместить в ссылку, для рекламы полезно.

2020-01-29 06:44 UTC, tahavn commented on Index.html
> +        </ul>
повторение классов у разных по дизайну элементов, возникнут сложности при стилизации

2020-02-01 10:02 UTC, IdiyatovAlexandr commented on Index.html
> +        </h1>
Насколько критично что у нас на странице не будет h1?

2020-02-01 10:02 UTC, IdiyatovAlexandr commented on Index.html
> +        </h1>
всмысле в коде не будет)

2020-02-03 15:39 UTC, tahavn requested changes
Комментарий

2020-02-03 15:39 UTC, tahavn commented on Index.html
> +        </h1>
Не критично или нет решит сео специалист. Но мы можем его указать его скрытым для этого блока

2020-02-04 16:48 UTC, tahavn requested changes
правки ДЗ 2-3

2020-02-04 16:48 UTC, tahavn commented on CategoryProducts/index.html
> +            <img class="header-button header-search-button" src="search.png" alt="serach">
путь к изображению не верный

2020-02-04 16:48 UTC, tahavn commented on CategoryProducts/index.html
> +        <span class="title-text">Catalog</span>
этот блок ни как не относится к title, это breadcrumbs. их лучше объединить в отдельный блок, т.к. они будут на всех внутренних страницах

2020-02-04 16:48 UTC, tahavn commented on CategoryProducts/index.html
> +      </a>
у нас уже есть главная страница, сюда можем поставить ссылку на нее

2020-02-04 16:48 UTC, tahavn commented on CategoryProducts/index.html
> +          <li><a class="link" href="#">catalog</a></li>
т.к. мы находимся на этой странице то можно либо вместо ссылки использовать другой тег или у ссылки удалить атрибут href чтобы она стала не кликабельной

2020-02-04 16:48 UTC, tahavn commented on CategoryProducts/index.html
> +          <li><a class="products-link" href="#">APPAREL ADULTS</a></li>
если картинки будут как фон, то вопросов нет, но такие картинки лучше делать контентными, чтобы пользователь мог их заменить

2020-02-04 16:48 UTC, tahavn commented on CategoryProducts/index.html
> +      <p><a class="web design-link" href="#">Web Design — Direct Line Development</a></p>
здесь можно оставить только тег А

2020-02-04 16:48 UTC, tahavn commented on Index.html
> +          <li><a class="link" href="#">catalog</a></li>
эта страница уже есть, можно на нее поставить ссылку

2020-02-04 16:48 UTC, tahavn commented on Index.html
> +          <a class="products-link" href="#">ACCESSORIES</a>
нет изображений, контентные картинки лучше вставлять в верстку, чтобы было возможность их заменить из админ-панели к примеру

2020-02-04 16:48 UTC, tahavn commented on Index.html
> +          <p><button type="submit">join</button></p>
укажи placeholder и здесь можно обойтись без тега P. если нужна просто обертка то лучше использовать тег div. для P добавляют отступы.

2020-02-04 16:48 UTC, tahavn commented on CategoryProducts/index.html
> +          <p><button type="submit">join</button></p>
укажи placeholder и здесь можно обойтись без тега P. если нужна просто обертка то лучше использовать тег div. для P добавляют отступы.

2020-02-04 16:48 UTC, tahavn commented on Index.html
> +          <li><a href="#">instagram</a></li>
нет изображений соц. сетей

2020-02-04 16:48 UTC, tahavn commented on CategoryProducts/index.html
> +          <li><a href="#">instagram</a></li>
нет изображений соц. сетей

2020-02-04 16:48 UTC, tahavn commented on Index.html
> +      <p><a class="web design-link" href="#">Web Design — Direct Line Development</a></p>
здесь можно оставить только тег А

2020-02-05 11:28 UTC, IdiyatovAlexandr commented on CategoryProducts/index.html
> +          <li><a class="link" href="#">catalog</a></li>
а можно вот до такого состояния упростить <li>catalog</li> , или все же еще в span например обернуть?

2020-02-05 11:29 UTC, IdiyatovAlexandr commented on CategoryProducts/index.html
> +          <li><a class="link" href="#">catalog</a></li>
<li><a class="link" href="#">blog</a></li>
          <li>catalog</li>
          <li><a class="link" href="#">about us</a></li>

2020-02-05 15:53 UTC, tahavn requested changes
Выполняй следующее ДЗ

2020-02-05 15:53 UTC, tahavn commented on Index.html
> +          <label class="hidden" for="form-email">Email</label>
по дизайну он там не нужен, только если скрывать его, но тогда тоже особо от него толку не будет, так что здесь он лишний

2020-02-06 15:24 UTC, tahavn requested changes
правки дз

2020-02-06 15:24 UTC, tahavn commented on CategoryProducts/index.html
> +            <img class="products-img" src="/images/products6.jpg" alt="apparel adults"></li>
заголовок блока и картинку лучше всегда размещать в одной ссылке

2020-02-06 15:24 UTC, tahavn commented on Index.html
> +          <img class="products-img" src="/images/products4.jpg" alt="accessories">
1. Заголовок и картинку в таких блоках лучше делать в одной ссылке
2. делаем пока только структуры для видимых элементов страницы

2020-02-06 15:24 UTC, tahavn commented on Index.html
> +          <button class="slider_nav-item"></button>
молодей, верное замечание сделал. тип лучше указать, здесь подойдет type="button". если тип не указан то браузер самостоятельно его подставит, и некоторые браузеры могут подставить тип submit который здесь ну совсем не нужен

2020-02-09 08:00 UTC, IdiyatovAlexandr commented on Index.html
> +          <img class="products-img" src="/images/products4.jpg" alt="accessories">
> 2\. делаем пока только структуры для видимых элементов страницы
А что у нас будет относиться к скрытым элементам?

2020-02-09 15:01 UTC, tahavn requested changes
Правки

2020-02-09 15:01 UTC, tahavn commented on Index.html
> +          <li><a class="link" href="http://127.0.0.1:5500/CategoryProducts/Index.html">catalog</a></li>
не верный путь.
такое откроется только на твоем пк

2020-02-10 16:15 UTC, tahavn reviewed
ДЗ

2020-02-10 16:16 UTC, merged