третья страница "toys"
dl-academy-edu/vt-idiyatov-alexander pull request #3
Opened 2020-02-11 16:57 UTC by IdiyatovAlexandr

2020-02-11 17:23 UTC, tahavn requested changes
правки дз

2020-02-11 17:23 UTC, tahavn commented on folders/Toys/Index.html
> +          <input id="form-color-white" type="checkbox" name="white">
такой вариант подходит, но при отправки данных на сервере чаще всего обрабатывают значение value.
можно указать name=color, а в value уже указать цвета.

в макете есть выбранный пункт, в разметке не видно этого

2020-02-11 17:23 UTC, tahavn commented on folders/Toys/Index.html
> +          <input id="form-delivery-fast" type="radio" name="fast shipping">
1. в макете есть выбранный пункт, в разметке не видно этого.
2. чтобы radio работали как группа, то у них должно быть одинаковое имя.  имена с пробелами можно делать, но лучше если надо несколько слов, то лучше через дефис или нижнее подчеркивание. потребуется указать value

2020-02-11 17:23 UTC, tahavn commented on folders/Toys/Index.html
> +          <input id="form-amount-50" type="radio" name="20-50">
чтобы radio работали как группа, то у них должно быть одинаковое имя.  имена с пробелами можно делать, но лучше если надо несколько слов, то лучше через дефис или нижнее подчеркивание. потребуется указать value

2020-02-11 17:23 UTC, tahavn commented on folders/Toys/Index.html
> +          </li>
каша в коде.
при длинных строках каждый тег лучше переносить на новую строку.
так же читабельнее http://joxi.ru/E2pXeXQUavl5y2 + заголовок тоже лучше обернуть в тег, понадобиться при стилизации

2020-02-13 15:04 UTC, tahavn requested changes
правки

2020-02-13 15:04 UTC, tahavn commented on folders/Toys/Index.html
> +        <button class="slider_toys" type="button">4</button>
1. это не слайдер, это пагинация - навигация для страниц, ее надо через ссылки делать.
2. в разметке отсутствуют кнопки/ссылки вперед/назад

2020-02-14 17:17 UTC, tahavn requested changes
правки

2020-02-14 17:17 UTC, tahavn commented on folders/Toys/Index.html
> +      </ul>
ну а кнопки/ссылки вперед/назад http://joxi.ru/v29oOoVczjKLvr

2020-02-14 17:17 UTC, tahavn commented on folders/Blog/index.html
> +        <li><a class="pagination-link" href="#">4</a></li>
нет кнопок/ссылок вперед/назад

2020-02-14 17:17 UTC, tahavn commented on folders/Blog/index.html
> +            given marketplace.</p>
в подобных блоках лучше когда и название и картинка это ссылки.
можно сделать отдельными ссылками, но можно 
картинку, дату, и название статьи объединить одной ссылкой.

2020-02-14 20:58 UTC, IdiyatovAlexandr commented on folders/Toys/Index.html
> +      </ul>
блин, я их даже не увидел)

2020-02-16 10:05 UTC, tahavn reviewed
ДЗ

2020-02-16 10:05 UTC, merged